### ISSUE TITLE
what should the callback URL be?

### ISSUE THREAD

**Issue by choxi** [uraway/electron-oauth-github#4]
When registering a GitHub app, it asks for an oauth callback URL. I wasn't sure what to put there since the oauth request is coming from an Electron app, but when I try to put in a random website domain I get a 404 after the step where I enter my GitHub username and password.

Thanks for the help, hope I'm not missing something obvious.

**Comment by uraway** [comment]
Hi, @choxi. I upgraded this library. 
You can put any callback URL like 'example.com'.

Could you try new example?

**Comment by choxi** [comment]
Yup, I tried it using `http://localhost` and that works as well. Thank you!

**Comment by uraway** [comment]
Thanks. I will close this issue.
